In [1]:
import pandas as pd

tensors_path = 'tensors/'
data = pd.read_csv('data/final.csv')
data.dropna(inplace=True)
y = [float(t) for t in data['is_sql'].tolist()]
len(y)

3994

In [2]:
def get_tensors(tensors_file):
    tensors = []
    with open(tensors_path + tensors_file, "r") as f:
        for line in f:
            tensors.append([float(t) for t in line.split('\t')])
    return tensors

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np
import warnings
warnings.filterwarnings("ignore")

SEED = 1316

Class 0 = natural

Class 1 = SQL query

Class 2 = SQL injection

In [5]:
for file in ["tensors_roberta.tsv","tensors_roberta_finetunned.tsv",
             "tensors_roberta_custom_tokenizer.tsv", "tensors_roberta_finetunned_custom_tokenizer.tsv"]:

    print("="*len(file))
    print(file)
    print("="*len(file))
    
    tensors = get_tensors(file)
    
    X_train, X_test, y_train, y_test = train_test_split(tensors, y, test_size=0.4, 
                                                    stratify=y, random_state=SEED)
    
    
    clf = LogisticRegression(random_state=SEED).fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(confusion_matrix(y_test, y_pred))
    acc = accuracy_score(y_test, y_pred)
    acc = round(acc*100, 2)
    print(f"\nAccuracy = {acc}%\n")

tensors_roberta.tsv
[[796   0   2]
 [  0 400   0]
 [  2   0 398]]

Accuracy = 99.75%

tensors_finetunning_roberta.tsv
[[796   0   2]
 [  0 400   0]
 [  2   0 398]]

Accuracy = 99.75%

tensors_tokenizer_roberta.tsv
[[778   4  16]
 [  4 395   1]
 [ 18   1 381]]

Accuracy = 97.25%

tensors_tokenizer_roberta_finetunning.tsv
[[794   0   4]
 [  1 399   0]
 [ 22   1 377]]

Accuracy = 98.25%

tensors_tokenizer_finetunning3_roberta.tsv
[[793   1   4]
 [  1 399   0]
 [ 23   0 377]]

Accuracy = 98.19%

